:@echo off

cd /d %~dp1

del /Q FIREEEE_DATA_RAM.o
del /Q FIREEEE_DATA_RAM.vcd

iverilog -o FIREEEE_DATA_RAM.o -s FIREEEE_DATA_RAM_tb ^
-g2012 ../../FIREEEE_DATA_RAM_tb.sv ^
../../FIREEEE_DATA_RAM.v ^
../../../01_FIREEEE_DCLK_EDGE_DET/FIREEEE_DCLK_EDGE_DET.v ^
../../../02_FIREEEE_RAM/SDPRAM_SINGLECLK.v ^
../../../02_FIREEEE_RAM/FIREEEE_RAM.v ^
../../../03_FIREEEE_RAM_CTRL/FIREEEE_RAM_CTRL.v

vvp FIREEEE_DATA_RAM.o

gtkwave FIREEEE_DATA_RAM.vcd
